zeek/zeek-client

- CMakeLists.txt
- zeek-client
This expands support for cluster topology configurations, reworks the supported commands a bit for consistency, adds a few test commands for driving testcases, and introduces support for config files.
There's also a change around the use of `endpoint.peer()`: I noticed that in the testsuite's docker-compose setups the client sometimes complains about not being able to connect to the controller, despite the fact that the `peer()` command supports a retry. I'm speculating that there are network conditions that this retry doesn't catch. For now I've added an explicit, configurable retry within the `connect()` function provided by the client. Worth some digging.
> zeek-client feature set update for the next Cluster Controller iteration

- zeek-client
This PR contains two main parts:
- It refactors the translation of Zeek's enums to/from Python `enum.Enum` objects. This is a bit tricky since Zeek renders enums into fully-scoped strings ("Foo.Bar.VAL_1") with no immediate equivalent to such scoping in Python. The PR adds a new class hierarchy branch for enums to make the rendering of enums to/from Broker more similar to that of other records.
- More importantly, it adds a `get-nodes` command to support the new corresponding functionality on the Zeek side. 
For a deployed configuration this might look as follows:
```
$ zeek-client get-nodes | jq .
{
"instance-1": {
"controller-swinetrek": {
"cluster_role": null,
"mgmt_role": "CONTROLLER",
"pid": 2137201,
"state": "RUNNING"
},
"instance-1": {
"cluster_role": null,
"mgmt_role": "AGENT", …
```
> Improve zeek-client's enum handling and add get-nodes command 

- zeek-client
This avoids a runtime error in the new Broker and is cleaner anyway.
> Create Broker enums directly via Broker.Enum()

- zeek-client
Just like in zeek-script: run the built-up argparse parser through argcomplete to provide command-line completion.
> Support argcomplete when available

- zeek-client
This is the companion PR to zeek/zeek#2081, implementing the client command. There are a lot more changes in the client for this one than in the controller, mainly because more legwork was required to support representations in Broker, JSON, and INI files.
> Add `get-config` command

- zeek-client
This contains two bugfixes to the rendering of cluster configs retrieved from the controller.
> Be more precise when rendering instances to .ini/.json

- tests/test_cli.py
- tests/test_config.py
- tests/test_rendering.py
- zeek-client
- zeekclient/cli.py
- zeekclient/config.py
- zeekclient/consts.py
- zeekclient/controller.py
- zeekclient/logs.py
- zeekclient/types.py
These are client-only changes that make two aspects of its configuration that so far could only happen via command line flags handled uniformly: the controller to connect to, and the verbosity level.
This also permits simpler cluster config .ini files: in configs where agents connect to the controller, it will often be the case that the `instances` section is simply a list of instance names that is already expressed via the names of instances that nodes declare themselves running on. You can now omit the instance section in that case, allowing nodes to imply the instances list.
> Minor updates to client configuration and parsing cluster configs from .ini

- zeekclient/cli.py
Just a small tweak here, as companion PR to zeek/zeek#2172. This is covered by zeek/zeek-testing-cluster#10, not via the local unit tests.
> Tweak set-config results rendering for empty, successful agent responses

- tests/broker.py
- tests/test_config.py
- tests/test_controller.py
- zeekclient/cli.py
- zeekclient/config.py
- zeekclient/controller.py
- zeekclient/events.py
- zeekclient/types.py
This is the companion PR to zeek/zeek#2197. Also contains a rework of `Controller.connect()`, which didn't need the loops around the peering, but did need to timeout the `get()` on the status subscriber.
> Separate `set-config` into `stage-config` and `deploy`, add `deploy-config` to combine both

- CMakeLists.txt
- zeekclient/cli.py
- zeekclient/events.py
This adds a command to restart all or specific Zeek cluster nodes in the current deployment. Also includes a cmake tweak to ensure we only install the .py files in the `zeekclient` directory, not any .pyc and related ones that running unit tests might have created.
Companion PR to zeek/zeek#2202.
> Add `restart` command

- LICENSE
- README.md
- tests/test_rendering.py
- zeekclient/types.py
When running all cluster management (controller, agent, and client) on a single machine, the need to specify an instance at all is a hassle and we can imply the local instance. This also means that examples become fully self-contained since installation-specific details like the hostname no longer show up.
Also fleshes out README and adds the usual license.
> Simplify configs for single-host scenarios

- tests/broker.py
- tests/test_controller.py
- zeekclient/cli.py
- zeekclient/controller.py
- zeekclient/events.py
The client was so far not robust at all to unexpected response data (i.e., any events not in response to request events it had just submitted). This makes the client skip any unexpected responses. Timeouts etc still apply, but such unexpected responses simply get dropped on the floor. A unit test covers this, and in local testing I can now run multiple clients in parallel against the same controller.
> Event-filtering fixes

- .github/workflows/test.yml
- tests/test_cli.py
- tests/test_config_io.py
- tests/test_config_overrides.py
- tests/test_controller.py
- tests/websocket.py
- zeekclient/controller.py
Connecting to a non-existant controller could hit an infinite-retries loop because of a straightforward bug in the retry logic. A unit test now verifies that this works. Also contains minor cleanups.
> Fix for infinite connection attempts and some minor cleanup

- .github/workflows/test.yml
- tests/test_cli.py
- zeek-client
@dopheide-esnet spotted that `zeek-client` was still lacking the usual `sys.path` tweak to reliably locate its Zeek-bundled Python module. This adds this tweak and adds a test for it.
> Fix Zeek-bundled install's Python module handling; add test

- .gitignore
- .pre-commit-config.yaml
- CMakeLists.txt
- Makefile
- man/build.py
- man/zeek-client.1
This uses the `argparse_manpage` Python package, which does a reasonably good job at turning the argparse parser into a manpage. The setup is manual (you have to run `man/build.py` to update the manpage), and installation happens only when bundled with Zeek (like for `zkg` etc).
Resolves #20.
> Add manual page.

- tests/test_cli.py
- tests/test_config_io.py
- tests/test_types.py
- zeekclient/cli.py
- zeekclient/types.py
This adds support for creating nodes with an optional metrics port, to read it from a .ini, and to serialize to/from JSON. Includes test cases.
Companion to zeek/zeek#3812.
> Additions for a metrics_port in the node state.

- zeekclient/types.py
There is bug with `cpu_affinity` field in deploy configuration. When it's placed in config, commands like `deploy-config`/`stage-config` fail with "request timed out" error.
`Controller` expects an `Integer` type for the field but actually gets the `Count`.
The pull request provides a solution
Just by correcting type for `cpu_affinity`
Closes #34
> fix `deploy-config`/`stage-config` bug relative to `cpu_affinity` config field

- .pre-commit-config.yaml
- Makefile
- man/build.py
- pyproject.toml
- tests/test_brokertypes.py
- tests/test_cli.py
- tests/test_config_io.py
- tests/test_config_overrides.py
- tests/test_controller.py
- tests/test_types.py
- tests/websocket.py
- zeek-client
- zeekclient/__init__.py
- zeekclient/brokertypes.py
- zeekclient/cli.py
- zeekclient/config.py
- zeekclient/controller.py
- zeekclient/events.py
- zeekclient/logs.py
- zeekclient/ssl.py
- zeekclient/types.py
This PR modernizes the project and moves linting to ruff like which we already use in many other Zeek Python projects.
> Modernize project

- .github/workflows/test.yml
- man/build.py
- man/zeek-client.1
- pyproject.toml
- zeekclient/cli.py
Part of https://github.com/zeek/zeek/issues/3239
> Upgrade python requirement to 3.9

- tests/test_controller.py
- tests/websocket.py
- zeekclient/controller.py
After the upgrade to Python 3.9, some of the types we were using for the websocket package changed. This fixes the code to use the right types.
> Use correct types for websocket exceptions

- zeek-client
This was removed in f93b8e193773a667eaaba5bb5f99cf05f1c478dd but causes problems on systems without Internet access.
> Revert modification of sys.path when importing zeekclient

- tests/test_config_overrides.py
- zeekclient/config.py
Accidentally found out that the --controller option doesn't support IPv6 addresses, so here's a first attempt.  I'm hoping to build test cases once I remember how to get those to run.
> Supporting IPv6 addresses for the --controller option

- tests/test_controller.py
- zeek-client
- zeekclient/config.py
- zeekclient/controller.py
There's new behavior in Zeek's WebSocket stack that causes Broker errors to shine through, which could confuse the client. Unexpected messages are now simply skipped.
This also adds a new debug level which traces the WebSocket I/O to stderr, helpful for debugging.
> Loosen the message I/O with the controller to not error out upon wrong message type
